/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary;

import Control.CertaintyFactor;
import Control.JsonHandler;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONObject;

/**
 *
 * @author Asus
 */
public class DiseaseMenu extends javax.swing.JFrame {

    /**
     * Creates new form DiseaseMenu
     */
    public DiseaseMenu() {
        initComponents();
        DefaultTableModel model = 
                (DefaultTableModel)this.symptomsListTable.getModel();
        
        CertaintyFactor cf = new CertaintyFactor();
        List<String> symptoms = cf.getSymptoms();
        model.setRowCount(symptoms.size());
        model.setColumnCount(3);
        
        for (int i = 0; i < symptoms.size(); i++) {
            model.setValueAt(symptoms.get(i), i, 0);
            model.setValueAt(0.0, i, 1);
        }
        
//        symptomsListTable.changeSelection(1, 1, false, false);
//        symptomsListTable.editCellAt(1, 1);
//        symptomsListTable.getEditorComponent().requestFocusInWindow();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        symptomsListTable = new javax.swing.JTable();
        diseaseNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addNewDiseaseButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        symptomsListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Gejala", "Bobot", "-"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(symptomsListTable);

        jLabel1.setText("Nama Penyakit");

        addNewDiseaseButton.setText("Tambah Penyakit");
        addNewDiseaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDiseaseButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Tutup");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diseaseNameTextField)
                    .addComponent(jLabel1)
                    .addComponent(addNewDiseaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(diseaseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addNewDiseaseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void addNewDiseaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDiseaseButtonActionPerformed
        String diseaseName = this.diseaseNameTextField.getText();
        if (diseaseName.equals("")) {
            JOptionPane.showMessageDialog(null, 
                    "Anda harus memberi nama penyakit");
            return;
        }
        
        if (this.symptomsListTable.isEditing()) {
            this.symptomsListTable.getCellEditor().stopCellEditing();
        }
        
        DefaultTableModel model = 
                (DefaultTableModel)this.symptomsListTable.getModel();
        
        int numSelectedSymptoms = 0;
        JSONObject symptoms = new JSONObject();
        for (int i = 0; i < model.getRowCount(); i++) {
            Object checkbox = model.getValueAt(i, 2);
            if (checkbox != null && (boolean)checkbox == true) {
                String symptom = model.getValueAt(i, 0).toString();
                double weight = 
                        Double.parseDouble(model.getValueAt(i, 1).toString());
                symptoms.put(symptom, weight);
                numSelectedSymptoms++;
            }
        }
        
            
        if (numSelectedSymptoms <= 0) {
            JOptionPane.showMessageDialog(null, 
                    "Anda harus memilih setidaknya satu gejala");
            return;
        }
        
        JSONObject data = new JSONObject();
        data.put("disease", diseaseName);
        data.put("symptoms", symptoms);
        
        List<Object> oldData = JsonHandler.readJsonFile("config/disease.json");
        oldData.add(data);
        JsonHandler.updateJsonFile("config/disease.json", oldData);
        JOptionPane.showMessageDialog(null, 
                    "Data penyakit baru berhasil ditambahkan");
        this.dispose();
    }//GEN-LAST:event_addNewDiseaseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiseaseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiseaseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiseaseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiseaseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiseaseMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewDiseaseButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField diseaseNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable symptomsListTable;
    // End of variables declaration//GEN-END:variables
}
